# Generated by Django 3.0.5 on 2020-04-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(max_length=20, verbose_name='Tipo de entidade')),
            ],
            options={
                'verbose_name': 'Tipo de Entidade',
                'verbose_name_plural': 'Tipos de Entidade',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('company_name', models.CharField(max_length=120, verbose_name='Razão Social')),
                ('fantasy_name', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('address_name', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city_code', models.CharField(blank=True, max_length=7, verbose_name='Código do município')),
                ('city_name', models.CharField(max_length=100, verbose_name='Código do município')),
                ('state_code', models.CharField(max_length=2, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('country_code', models.CharField(blank=True, max_length=4, verbose_name='Código do país')),
                ('country_name', models.CharField(blank=True, max_length=40, verbose_name='País')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Telefone')),
                ('state_registration', models.CharField(blank=True, max_length=16, verbose_name='IE')),
                ('entity_type', models.ManyToManyField(blank=True, to='upload.EntityType')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('date_lastupdated', models.DateField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(max_length=2, verbose_name='Modalidade de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='Número do documento')),
                ('document_key', models.CharField(max_length=44, primary_key=True, serialize=False, verbose_name='Chave do documento')),
                ('document_date', models.DateField(verbose_name='Data de emissão')),
                ('doc_file', models.FileField(upload_to='docs/', verbose_name='Arquivo do documento')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_document_set', to='upload.Entity', verbose_name='transportador')),
                ('deliver_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_to_document_set', to='upload.Entity', verbose_name='entrega')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_document_set', to='upload.Entity', verbose_name='destinatário')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_document_set', to='upload.Entity', verbose_name='emissor')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
