# Generated by Django 3.0.4 on 2020-03-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cnpj_recipient',
            field=models.CharField(max_length=14, verbose_name='CNPJ destinatário'),
        ),
        migrations.AlterField(
            model_name='document',
            name='cnpj_sender',
            field=models.CharField(max_length=14, verbose_name='CNPJ emissor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to='docs/', verbose_name='Arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_date',
            field=models.DateField(verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_key',
            field=models.CharField(max_length=44, null=True, verbose_name='Chave do documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=30, verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de upload'),
        ),
    ]
